### ISSUE TITLE
[MJAR-121] blank space and new line in manifest classpath

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-jar-plugin#161]
**[julio benitez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdbenitez)** opened **[MJAR-121](https://issues.apache.org/jira/browse/MJAR-121?redirect=false)** and commented

If a project depends on another project,  when we generate the second project the classpath in manifest includes a extra blank space like this.

Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven
Built-By: jbe
Build-Jdk: 1.6.0_10
Class-Path: project_1-1.0.jar jdom-1.0.jar log4j-1.2.9.jar commons-col
lections-3.2.jar

Example attached

---

**Affects:** 2.1, 2.2

**Attachments:**
- [sample_2poms.ZIP](https://issues.apache.org/jira/secure/attachment/12716790/sample_2poms.ZIP) (_5.61 kB_)
- [test_2poms_b.ZIP](https://issues.apache.org/jira/secure/attachment/12716745/test_2poms_b.ZIP) (_6.26 kB_)

**Comment by jira-importer** [comment]
**[Joerg Schaible](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=joehni)** commented

And what's now actually your problem?

**Comment by jira-importer** [comment]
**[julio benitez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdbenitez)** commented

Maven adds a blank space inside classpath, in the example commons-collections-3.2.jar is broken by a white space and a new line. The result is a class not found on execution.  I atached a new example with code that imports and uses commons-collections class.

**Comment by jira-importer** [comment]
**[julio benitez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdbenitez)** commented

> java -jar project_2-1.0.jar

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/co
llections/MultiMap
Caused by: java.lang.ClassNotFoundException: org.apache.commons.collections.Mult
iMap
at java.net.URLClassLoader$1.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClassInternal(Unknown Source)
Could not find the main class: com.test.project_2.Example. Program will exit.

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

This behavior is correct as per the JAR File Specification.

See the section "Line length:" at http://java.sun.com/j2se/1.5.0/docs/guide/jar/jar.html#Notes%20on%20Manifest%20and%20Signature%20Files

**Comment by jira-importer** [comment]
**[julio benitez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdbenitez)** commented

sorry.
