### ISSUE TITLE
[MJAR-20] Don't create empty jars

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-jar-plugin#216]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** opened **[MJAR-20](https://issues.apache.org/jira/browse/MJAR-20?redirect=false)** and commented

Creating empty jars is confusing, it should just print a warning

use case:
parent pom attaching test jar, some subprojects may not have tests, why create jars for them?

---

**Affects:** 2.0

**Attachments:**
- [MJAR-20.patch](https://issues.apache.org/jira/secure/attachment/12716783/MJAR-20.patch) (_2.51 kB_)
- [MJAR-20-02.patch](https://issues.apache.org/jira/secure/attachment/12716768/MJAR-20-02.patch) (_13.03 kB_)

**Issue Links:**
- [MJAR-27](https://issues.apache.org/jira/browse/MJAR-27) jar:sign doesn't check if project produces an artifact

- [MJAR-105](https://issues.apache.org/jira/browse/MJAR-105) Regression: Build fails for an empty main jar with 2.2

9 votes, 11 watchers

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Another use case

parent pom attaching test jar, maven creates an empty test jar for that pom project

**Comment by jira-importer** [comment]
**[Jerome Lacoste](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lacostej)** commented

I believe this to duplicate MJAR-27 which has a patch. Make sure that the patch cover all cases reported by Carlos in this issue.

**Comment by jira-importer** [comment]
**[Mike Perham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mperham)** commented

I don't see how MJAR-27 solves Carlos's usecase.  The parent POM can mandate that test-jars are created for all child projects.  If one of those child projects has no src/test/java code but has src/main/java code, it will get an empty test-jar even though it is a java module.

**Comment by jira-importer** [comment]
**[Jochen Wiedmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jochen.wiedmann@gmail.com)** commented

Currently the jar plugin checks, whether the directory being archived exists. If so, a warning is currently issued.

I suggest to introduce a property "createEmptyArchive", which defaults to false. If the property is set to true, then the plugins behaviour remains unchanged. Otherwise, no jar file is created. This is what the attached patch does.

If the directory does exist, one could check for files. I leave it to the patches reviewer to decide whether this makes sense. A performance penalty is not to be expected, because one can stop searching as soon as the first file is found.

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

I did'n add the option to create an empty jar because I don't see any reason for it

**Comment by jira-importer** [comment]
**[Brett Porter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=brettporter)** commented

I have reverted r417029 as it caused a regression (integration tests 94, 89, 88, 85, 81, 77, 72, 43, 41, 30)

Caused by: org.apache.maven.artifact.installer.ArtifactInstallationException: Error installing artifact: File c:\home\brett\scm\maven\components\maven-core-it\it0094\test\target\classes does not exist
at org.apache.maven.artifact.installer.DefaultArtifactInstaller.install(DefaultArtifactInstaller.java:84)
at org.apache.maven.plugin.install.InstallMojo.execute(InstallMojo.java:104)
... 19 more
Caused by: java.io.IOException: File c:\home\brett\scm\maven\components\maven-core-it\it0094\test\target\classes does not exist
at org.codehaus.plexus.util.FileUtils.copyFile(FileUtils.java:798)
at org.apache.maven.artifact.installer.DefaultArtifactInstaller.install(DefaultArtifactInstaller.java:70)
... 20 more

Please reapply, create a test to replicate this issue, then fix the issue.

**Comment by jira-importer** [comment]
**[Rodrigo Ruiz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nodens2k)** commented

My two cents :-)

IMHO, if there is no contents to put into the jar, the plugin should do nothing. I have followed this approach and made a modification in trunk (2.3-SNAPSHOT).

I have verified the modification does not break the current tests, and added two new integration tests for verifying the altered behaviour.

I have attached my modification in patch format (MJAR-20-02.patch). The patch includes the modification to AbstractJarMojo.java, and the new integration tests.

I hope this helps,
Rodrigo

**Comment by jira-importer** [comment]
**[Rodrigo Ruiz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nodens2k)** commented

Hi Paul,

My patch adds a configuration option "createEmptyArchive" that can be set to true for forcing the jar creation. I see two ways of preventing what you describe:

1. Set the property default value to true. This means keeping the current default behaviour, allowing the developer to modify it at will.

2. Forcing its value to true when the classifier is null (main jar). This means changing the body of the isCreateEmptyArchive() method to:

   protected boolean isCreateEmptyArchive() {
   return createEmptyArchive || getClassifier() == null;
   }

I would prefer the second option, because I think this is what most people would expect as the default behaviour (no test jar if there are no tests).
