### ISSUE TITLE
[MJAR-31] [webstart] NPE when signing dependencies

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-jar-plugin#220]
**[Michael Böckling](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=buddycasino)** opened **[MJAR-31](https://issues.apache.org/jira/browse/MJAR-31?redirect=false)** and commented

In JarSignMojo, the call to this.signedjar.getPath() produces a NPE, because in JnlpMojo:863, signJar.setSignedJar() has been commented out.

Stacktrace:

[debug] jarsigner executable=[C:\Programme\Java\jdk1.5.0_06\jre\..\bin\jarsigner
.exe]
[INFO] -------------------------------------------------------------------------
&mdash;
[ERROR] BUILD ERROR
[INFO] -------------------------------------------------------------------------
&mdash;
[INFO] Failure to run the plugin:

[INFO] -------------------------------------------------------------------------
&mdash;
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Failure to run the plugi
n:
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:556)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLi
fecycle(DefaultLifecycleExecutor.java:472)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau
ltLifecycleExecutor.java:451)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan
dleFailures(DefaultLifecycleExecutor.java:303)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen
ts(DefaultLifecycleExecutor.java:270)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi
fecycleExecutor.java:139)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)

    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

Caused by: org.apache.maven.plugin.MojoExecutionException: Failure to run the pl
ugin:
at org.codehaus.mojo.webstart.JnlpMojo.execute(JnlpMojo.java:479)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi
nManager.java:415)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa
ultLifecycleExecutor.java:531)
... 16 more
Caused by: java.lang.NullPointerException
at org.apache.maven.plugin.jar.JarSignMojo.signJar(JarSignMojo.java:227)

        at org.apache.maven.plugin.jar.JarSignMojo.execute(JarSignMojo.java:185)
    
        at org.codehaus.mojo.webstart.JnlpMojo.signJars(JnlpMojo.java:865)
        at org.codehaus.mojo.webstart.JnlpMojo.execute(JnlpMojo.java:441)
        ... 18 more

---

**Attachments:**
- [MOJO-295.diff](https://issues.apache.org/jira/secure/attachment/12716702/MOJO-295.diff) (_842 bytes_)

10 votes, 6 watchers

**Comment by jira-importer** [comment]
**[Jerome Lacoste](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lacostej)** commented

It's my understanding that the first part of this issue was fixed as part of the commit to MJAR-24.
As with the 2nd part, I don't understand why project.getArtifact() can return null. Can someone pinpoint me to the real reason behind that second NPE?

**Comment by jira-importer** [comment]
**[Jerome Lacoste](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lacostej)** commented

On 4/13/06, Tim Kettler <tim.kettler@     .edu> wrote:

> I just deleted my local repo and checked out the latest versions of the jar and webstart
> plugins from svn and can't reproduce the second NPE from MJAR-31 anymore. So this is fixed
> somehow already (at least for me).

Thanks for the report.
I lean toward closing the issue and reopening it if someone rereports it.
The whole thing is fishy and I'd rather know why the getArtifact() can return null before making the change.
I answered to Brett on the devel list if it is possible to make MavenProject#setArtifact throw an NPE if null is passed.
If you encounter that issue, consider making that change yourself.

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

the last comment on this issue seems to indicate that this is no longer happening. Do we have a test case to express the problem, and is it still an issue?

**Comment by jira-importer** [comment]
**[Adrian](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apill)** commented

I get this error also with the latest builds as of today.

**Comment by jira-importer** [comment]
**[Adrian](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apill)** commented

Has this fix been released into a stable build yet? I said in my previous comment that I still have the issue. However, I have not checked out and compiled the latest source. I am simply using the currently deployed artifacts.

**Comment by jira-importer** [comment]
**[Mike Perham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mperham)** commented

Jerome, I deleted your spurious comments as you requested.
