### ISSUE TITLE
[MJAR-142] 'Negative time' when trying to create an empty jar

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-jar-plugin#304]
**[bblasi bblasi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bblasi)** opened **[MJAR-142](https://issues.apache.org/jira/browse/MJAR-142?redirect=false)** and commented

When I try to run 'package' on a multi-module project one of the modules fails. The only difference on this module being it will run an ant script so no jar, or an empty one up until now, would be generated.

Plugin 2.2 will do the job. Plugin 2.3 fails on '-X package' with:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:2.3.1:jar (default-jar) on project ETRAMPackager: Error assembling JAR: Negative time -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:2.3.1:jar (default-jar) on project ETRAMPackager: Error assembling JAR
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:534)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error assembling JAR
	at org.apache.maven.plugin.jar.AbstractJarMojo.createArchive(AbstractJarMojo.java:223)
	at org.apache.maven.plugin.jar.AbstractJarMojo.execute(AbstractJarMojo.java:235)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:107)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.IllegalArgumentException: Negative time
	at java.io.File.setLastModified(File.java:1258)
	at org.codehaus.plexus.components.io.resources.PlexusIoFileResource.setLastModified(PlexusIoFileResource.java:148)
	at org.codehaus.plexus.components.io.resources.PlexusIoFileResource.setFile(PlexusIoFileResource.java:82)
	at org.codehaus.plexus.components.io.resources.PlexusIoFileResource.<init>(PlexusIoFileResource.java:73)
	at org.codehaus.plexus.components.io.resources.PlexusIoFileResourceCollection.addResources(PlexusIoFileResourceCollection.java:144)
	at org.codehaus.plexus.components.io.resources.PlexusIoFileResourceCollection.getResources(PlexusIoFileResourceCollection.java:181)
	at org.codehaus.plexus.components.io.resources.AbstractPlexusIoResourceCollection.getLastModified(AbstractPlexusIoResourceCollection.java:247)
	at org.codehaus.plexus.archiver.AbstractArchiver.isUptodate(AbstractArchiver.java:768)
	at org.codehaus.plexus.archiver.AbstractArchiver.checkForced(AbstractArchiver.java:799)
	at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.execute(AbstractZipArchiver.java:236)
	at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:852)
	at org.apache.maven.archiver.MavenArchiver.createArchive(MavenArchiver.java:543)
	at org.apache.maven.plugin.jar.AbstractJarMojo.createArchive(AbstractJarMojo.java:216)
	... 22 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ETRAMPackager
```

---

**Affects:** 2.3

1 votes, 4 watchers

**Comment by jira-importer** [comment]
**[bblasi bblasi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bblasi)** commented

Looks like I can't edit the issue: 2.3.1 is also affected.

**Comment by jira-importer** [comment]
**[Christian Pesch](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=cpesch)** commented

Some problem hier with maven-jar-plugin 2.4:

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.jangaroo:jangaroo-maven-plugin:0.9.11:package (default-package) on project social-studio-plugin: Failed to create the javascript archive
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to create the javascript archive
at net.jangaroo.jooc.mvnplugin.PackageMojo.execute(PackageMojo.java:133)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
... 19 more
Caused by: java.lang.IllegalArgumentException: Negative time
at java.io.File.setLastModified(File.java:1258)
at org.codehaus.plexus.components.io.resources.PlexusIoFileResource.setLastModified(PlexusIoFileResource.java:148)
at org.codehaus.plexus.components.io.resources.PlexusIoFileResource.setFile(PlexusIoFileResource.java:82)
at org.codehaus.plexus.components.io.resources.PlexusIoFileResource.\<init>(PlexusIoFileResource.java:73)
at org.codehaus.plexus.components.io.resources.PlexusIoFileResourceCollection.addResources(PlexusIoFileResourceCollection.java:144)
at org.codehaus.plexus.components.io.resources.PlexusIoFileResourceCollection.getResources(PlexusIoFileResourceCollection.java:185)
at org.codehaus.plexus.archiver.AbstractArchiver$1.hasNext(AbstractArchiver.java:435)
at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.createArchiveMain(AbstractZipArchiver.java:270)
at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.execute(AbstractZipArchiver.java:250)
at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:871)
at net.jangaroo.jooc.mvnplugin.PackageMojo.execute(PackageMojo.java:130)
... 21 more

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Christian,

You problem is not with maven-jar-plugin. Have a closer look at your stack trace. It says that the problem is at "net.jangaroo:jangaroo-maven-plugin" while executing the "package" goal. The error message is:
"Failed to create the javascript archive"

**Comment by jira-importer** [comment]
**[Ronald Wheeler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ronaldmwheeler)** commented

I think that Dennis is a bit off-base with cause and effect.

I have the same problem (or at least same symptom.

I am not sure if the above explanation relates to my problem.
The files involved are all downloaded from our SVN repo and have current dates.

It also seemed to be dependent on how fast the disk drive was. On a real disk it worked but on a RAM disk it did not.

It only happened on 1 project out of the 30 or so that makes up the application. My colleague had no trouble building it from the same SVN source.
We were only changing the POM file.

This is an error that I get when I execute my project in Eclipse/STS while running from a RAM drive.
If I run the same project running on Eclipse/STS while running on a regular disk drive it works.

It is pretty deep in the Maven code and looks like Maven/Plexus sends a bad argument to a Java function.

My only fix is to stop using my high speed version and build it in my slow disk based Eclipse and Maven (Same software just not on a RAM drive).

My stack trace:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4:single (default) on project util-pom-hibernate-mysql-tomcat: Execution default of goal org.apache.maven.plugins:maven-assembly-plugin:2.4:single failed: Negative time -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4:single (default) on project util-pom-hibernate-mysql-tomcat: Execution default of goal org.apache.maven.plugins:maven-assembly-plugin:2.4:single failed: Negative time
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:601)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.apache.maven.plugins:maven-assembly-plugin:2.4:single failed: Negative time
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
... 19 more
Caused by: java.lang.IllegalArgumentException: Negative time
at java.io.File.setLastModified(File.java:1344)
at org.codehaus.plexus.components.io.resources.PlexusIoFileResource.setLastModified(PlexusIoFileResource.java:174)
at org.codehaus.plexus.components.io.resources.PlexusIoFileResource.setFile(PlexusIoFileResource.java:107)
at org.codehaus.plexus.components.io.resources.PlexusIoFileResource.\<init>(PlexusIoFileResource.java:82)
at org.codehaus.plexus.components.io.resources.PlexusIoFileResource.\<init>(PlexusIoFileResource.java:66)
at org.codehaus.plexus.components.io.resources.PlexusIoFileResource.\<init>(PlexusIoFileResource.java:49)
at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.addParentDirs(AbstractZipArchiver.java:446)
at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.addResources(AbstractZipArchiver.java:394)
at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.createArchiveMain(AbstractZipArchiver.java:323)
at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.execute(AbstractZipArchiver.java:222)
at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:910)
at org.apache.maven.plugin.assembly.archive.archiver.AssemblyProxyArchiver.createArchive(AssemblyProxyArchiver.java:512)
at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:186)
at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:436)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
... 20 more

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Hi Ron,

I was merely pointing out that the stacktrace was not the same and the plugin where the failure occured was not the JAR plugin.

The real problem though doesn't seem to be in the JAR plugin, but rather in plexus-archiver, since we now have three different plugins that show the same problem; JAR, Assembly and Jangaroo.

**Comment by jira-importer** [comment]
**[Ronald Wheeler](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ronaldmwheeler)** commented

Problem persists in 3.1.1
Same symptom - a couple of projects can not be built using maven in Eclipse when running on a RAM drive (Windows 7) but will build from hard disk.

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

This error message belong to maven-assembly-plugin and is related to an old version.

**Comment by jira-importer** [comment]
**[Rakhunathan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mrakhunathan)** commented

Not really sure why the problem occurs, but found out the solution. The error occurs because, one or more file that you are trying to build, has a negative time.(file.getLastModified() returns a negative value). If its a huge project, might be hard to track which of them has gone wrong. Below code might help

package com.example;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ModifyAll {
public static void main(String[] args) throws IOException {
List\<File> folderList = new ArrayList<>();
List\<File> fileList = new ArrayList<>();

        File folder = new File("D:/Rakhu/Copy/projectfolder/src");
        FileVO baseFileVO = segregateFiles(folder);
        fileList.addAll(baseFileVO.getFileList());
        folderList.addAll(baseFileVO.getFolderList());
    
        for (int i = 0; i < folderList.size(); i++) {
            FileVO thisVO = segregateFiles(folderList.get(i));
            fileList.addAll(thisVO.getFileList());
            folderList.addAll(thisVO.getFolderList());
        }
    
        for (int i = 0; i < fileList.size(); i++) {
            Date dte = new Date();
            long milliSeconds = dte.getTime();
            System.out.println("Setting Time For " + fileList.get(i) + " as " + milliSeconds);
            fileList.get(i).setLastModified(milliSeconds);
        }
        System.out.println("Succesfully Modified..!!!");
    }
    
    public static FileVO segregateFiles(File folder) {
        List<File> folderList = new ArrayList<>();
        List<File> fileList = new ArrayList<>();
    
        File[] listOfFiles = folder.listFiles();
        for (int i = 0; i < listOfFiles.length; i++) {
            if (listOfFiles[i].isFile()) {
                fileList.add(listOfFiles[i]);
            } else {
                folderList.add(listOfFiles[i]);
            }
            System.out.println(listOfFiles[i]);
        }
        return new FileVO(fileList, folderList);
    }

}

FileVO.java
package com.example;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class FileVO {
List\<File> fileList = new ArrayList<>();
List\<File> folderList = new ArrayList<>();

    public FileVO(List<File> fileList, List<File> folderList) {
        this.fileList = fileList;
        this.folderList = folderList;
    }
    
    public List<File> getFileList() {
        return fileList;
    }
    
    public void setFileList(List<File> fileList) {
        this.fileList = fileList;
    }
    
    public List<File> getFolderList() {
        return folderList;
    }
    
    public void setFolderList(List<File> folderList) {
        this.folderList = folderList;
    }

}
