### ISSUE TITLE
[MJAR-164] Invalid shell bounce call command

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-jar-plugin#329]
**[Alexey Korchevsky](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mitallast)** opened **[MJAR-164](https://issues.apache.org/jira/browse/MJAR-164?redirect=false)** and commented

I create simple hello world project, and run build it by maven.

Maven run command "jar:jar", and it use org.codehaus.plexus-io component. This component throws exception:

```
Caused by: java.io.IOException: Failed to retrieve numeric file attributes using: '/bin/sh -c ls -1nlad /Users/mitallast/Sites/test/pom.xml'
	at org.codehaus.plexus.components.io.attributes.PlexusIoResourceAttributeUtils.executeLs(PlexusIoResourceAttributeUtils.java:281)
	at org.codehaus.plexus.components.io.attributes.PlexusIoResourceAttributeUtils.getFileAttributesByPath(PlexusIoResourceAttributeUtils.java:223)
	at org.codehaus.plexus.components.io.attributes.PlexusIoResourceAttributeUtils.getFileAttributes(PlexusIoResourceAttributeUtils.java:168)
	at org.codehaus.plexus.archiver.ArchiveEntry.createFileEntry(ArchiveEntry.java:157)
	... 32 more
```

Note, generated shell command is invalid:

```
/bin/sh -c ls -1nlad /Users/mitallast/Sites/test/pom.xml
```

Correct command like as

```
/bin/sh -c "ls -1nlad /Users/mitallast/Sites/test/pom.xml"
```

Shell option "-c" is short equivalent of "command". Value for this option is a shell command string. Plexus component didn't escape and not add quotes to generated "ls" command.

---
No further details from [MJAR-164](https://issues.apache.org/jira/browse/MJAR-164?redirect=false)

**Comment by jira-importer** [comment]
**[Jeff Molsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jmolsen)** commented

Editing comment (yet again) as I now think this error is slightly different than what I get:

The error I get:
Failed to retrieve numeric file attributes using: '/bin/sh -c ls -1nlad /opt/bamboo/bamboo4.0/xml-data/build-dir/path/to/pom.xml': Error while executing process. Cannot run program "/bin/sh": error=12, Not enough space

Through a little more research, I've found that the not enough space is referring to swap space needed for copying the running Java env into(see http://stackoverflow.com/questions/7829132/native-move-command-java-function which also points to https://wiki.jenkins-ci.org/display/JENKINS/IOException+Not+enough+space).  It seems either increasing swap size or reducing values for Xms and Xmx to Java can solve the issue I had.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

As described in latest comment:

> It seems either increasing swap size or reducing values for `Xms` and `Xmx` to Java can solve the issue I had.
