### ISSUE TITLE
[MJAR-174] NoClassDefFoundError while packaging using maven-jar-plugin:2.4 with Maven 3.1.1

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-jar-plugin#352]
**[Maruthi Shanmugam](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=maruthi_s)** opened **[MJAR-174](https://issues.apache.org/jira/browse/MJAR-174?redirect=false)** and commented

Exception while building with Maven 3.1.1 and maven-jar-plugin:2.4

Exception pasted for your reference :
WARNING] Error injecting: org.apache.maven.plugin.jar.JarMojo
java.lang.NoClassDefFoundError: org/codehaus/plexus/components/io/resources/PlexusIoResourceCollection
at java.lang.Class.getDeclaredConstructors0(Native Method)
at java.lang.Class.privateGetDeclaredConstructors(Class.java:2493)
at java.lang.Class.getDeclaredConstructors(Class.java:1901)
at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoi

---

**Affects:** 2.4

**Attachments:**
- [Maven_Error.txt](https://issues.apache.org/jira/secure/attachment/12716775/Maven_Error.txt) (_16.01 kB_)

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Can you please create a full working example project may be attach to the issue or create a github project.

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Unfortunately i don't get any feedback so i will close the issue. If you have an appropriate example please don't hesitate to reopen the issue.
