### ISSUE TITLE
[MJAR-259] Archiving to jar is very slow

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-jar-plugin#413]
**[Claes Nordmark](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nordmcla)** opened **[MJAR-259](https://issues.apache.org/jira/browse/MJAR-259?redirect=false)** and commented

Doing a stackdump while "maven-jar-plugin:3.1.0:jar (default-jar)" shows thread spending a lot of time in UnixNativeDispatcher.getgrgid.

This was not visible in java 8 and jar plugin version 2.6.

Our previous build time has been increased from 5min to 3h 30min.

Tested version Java 11 and 3.1.0 of maven-jar-plugin

 

```xml
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-jar-plugin</artifactId>
<version>${maven.jar.plugin.version}</version>
<configuration>
 <forceCreation>true</forceCreation>
 <archive>
  <index>true</index>
  <manifest>
    <addClasspath>true</addClasspath>
  </manifest>
 </archive>
</configuration>
</plugin>
 
```

 

```
java.lang.Thread.State: RUNNABLE
 at sun.nio.fs.UnixNativeDispatcher.getgrgid(java.base@11/Native Method)
 at sun.nio.fs.UnixUserPrincipals.fromGid(java.base@11/UnixUserPrincipals.java:129)
 at sun.nio.fs.UnixFileAttributes.group(java.base@11/UnixFileAttributes.java:208)
 - locked <0x000000067c2b31f0> (a sun.nio.fs.UnixFileAttributes)
 at sun.nio.fs.UnixFileAttributeViews$Posix.addRequestedPosixAttributes(java.base@11/UnixFileAttributeViews.java:214)
 at sun.nio.fs.UnixFileAttributeViews$Unix.readAttributes(java.base@11/UnixFileAttributeViews.java:362)
 at sun.nio.fs.AbstractFileSystemProvider.readAttributes(java.base@11/AbstractFileSystemProvider.java:94)
 at java.nio.file.Files.readAttributes(java.base@11/Files.java:1996)
 at org.codehaus.plexus.components.io.attributes.FileAttributes.<init>(FileAttributes.java:67)
 at org.codehaus.plexus.components.io.resources.PlexusIoFileResourceCollection.addResources(PlexusIoFileResourceCollection.java:156)
 at org.codehaus.plexus.components.io.resources.PlexusIoFileResourceCollection.getResources(PlexusIoFileResourceCollection.java:254)
 at org.codehaus.plexus.archiver.AbstractArchiver$1.hasNext(AbstractArchiver.java:506)
 at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.createArchiveMain(AbstractZipArchiver.java:256)
 at org.codehaus.plexus.archiver.zip.AbstractZipArchiver.execute(AbstractZipArchiver.java:234)
 at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:987)
 at org.apache.maven.archiver.MavenArchiver.createArchive(MavenArchiver.java:649)
 at org.apache.maven.plugins.jar.AbstractJarMojo.createArchive(AbstractJarMojo.java:224)
 at org.apache.maven.plugins.jar.AbstractJarMojo.execute(AbstractJarMojo.java:255)
 at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
 at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
 at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
 at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
 at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
 at java.util.concurrent.FutureTask.run(java.base@11/FutureTask.java:264)
 at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11/Executors.java:515)
 at java.util.concurrent.FutureTask.run(java.base@11/FutureTask.java:264)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11/ThreadPoolExecutor.java:1128)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11/ThreadPoolExecutor.java:628)
 at java.lang.Thread.run(java.base@11/Thread.java:834)
```

---

**Affects:** 3.1.0

**Issue Links:**
- [MSOURCES-119](https://issues.apache.org/jira/browse/MSOURCES-119) Archiving to jar is very slow

- [MJAR-261](https://issues.apache.org/jira/browse/MJAR-261) Upgrade plexus-archiver 3.7.0

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

outch ...need to upgrade plexus-io to most recent version. Thanks  Can you please VOTE on the DEV list against current maven-jar-plugin VOTE so I can stop the vote and respin an updated version...

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

[Claes Nordmark](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=nordmcla) Have you subscribed here  https://maven.apache.org/mailing-lists.html?

**Comment by jira-importer** [comment]
**[Anders Hammar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=afloom)** commented

What is needed is an upgrade to plexus-archiver v4.0.0+, see https://github.com/codehaus-plexus/plexus-archiver/blob/master/ReleaseNotes.md#plexus-archiver-400

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

Unfortunately this is not enough. plexus-archiver, plexus-utils and file-management must be upgraded and modello too cause of JavaDoc issues while creating the javadoc....I'm currently investigating this in more detail...

**Comment by jira-importer** [comment]
**[Anders Hammar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=afloom)** commented

What I can see, plexus-io is only pulled in by plexus-archiver. Upgrading plexus-archiver will update the transitive dependency of plexus-io. (This is for m-jar-p which this ticket is for.)

**Comment by jira-importer** [comment]
**[Karl Heinz Marbaise](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=khmarbaise)** commented

After analysing this. Upgrading plexus-archiver to 4.1.0 alone will not work.
* This will fail the build with `API incompatiblity`
* It is necessary to upgrade plexus-utils, maven-archiver to 3.4.0
* Furthermore needed to add maven-shared-utils to version 3.2.1 which
  is pulled by file-management.
* After upgrading them it is needed to fix two integration tests which relied on content of the `META-INF/MANIFEST.MF` which has changed in the meantime.
